spring.application.name=ghaith-bennasr-4ds9

spring.datasource.url=jdbc:mysql://localhost:3306/tpskidbbennasrghaith?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
